- name: News
  columns:
    - size: full
      widgets:
        - type: split-column
          max-columns: 3
          widgets:
            - type: rss
              title: "The Guardian"
              limit: 30
              style: detailed-list
              collapse-after: 5
              cache: 6h
              feeds:
                - url: https://feeds.theguardian.com/theguardian/uk/rss
                  title: The Guardian
                  # limit: 5
            - type: rss
              title: "Podcast RSS Feeds"
              limit: 10
              style: detailed-list
              collapse-after: 5
              cache: 6h
              feeds:
                - url: https://selfh.st/rss/
                  title: selfh.st
                - url: https://thisweekinlinux.com/rss
                  title: This Week in Linux
            - type: hacker-news
              cache: 6h
            - type: rss

