- name: threat intelligence
  columns:
    - size: full
      widgets:
        - type: split-column
          max-columns: 3
          widgets:
            - type: rss
              title: "CISA alerts"
              limit: 30
              style: detailed-list
              collapse-after: 5
              cache: 6h
              feeds:
                - url: https://www.cisa.gov/cybersecurity-advisories/all.xml
                  title: CISA Alerts
                  # limit: 5
            - type: rss
              title: "NIST Cybersecurity Insights"
              limit: 30
              style: detailed-list
              collapse-after: 5
              cache: 6h
              feeds:
                - url: https://www.nist.gov/blogs/cybersecurity-insights/rss.xml
                  title: NIST Cybersecurity Insights
                  # limit: 5
            - type: rss
              title: "CISCO Talos"
              limit: 30
              style: detailed-list
              collapse-after: 5
              cache: 6h
              feeds:
                - url: https://blog.talosintelligence.com/feeds/posts/default
                  title: CISCO Talos
                  # limit: 5
            - type: rss
              title: "Proofpoint Threat Research"
              limit: 30
              style: detailed-list
              collapse-after: 5
              cache: 6h
              feeds:
                - url: https://www.proofpoint.com/us/rss.xml
                  title: Proofpoint Threat Research
                  # limit: 5
            - type: rss
              title: "Unit42"
              limit: 30
              style: detailed-list
              collapse-after: 5
              cache: 6h
              feeds:
                - url: http://feeds.feedburner.com/Unit42
                  title: Unit42
                  # limit: 5